[package]
name = "audio_scripting"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
cpal = "0.16.0"
crossbeam-channel = "0.5.15"
dasp = { version = "0.11.0", features = ["all"] }
hound = "3.5.1"
ringbuf = "0.4.8"
rubato = "0.16.2"
